name: Pull Requests

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true
      - name: Install deps
        run: go mod download
      - name: Go lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s v2.7.2
          chmod a+x ./bin/golangci-lint
          ./bin/golangci-lint run ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true
      - name: Install deps
        run: go mod download
      - name: Go test
        run: go test ./...

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true
      - name: Install deps
        run: go mod download
      - name: Go build
        run: go build -o tanzia-web ./web

  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true
      - name: Install deps
        run: go mod download
      - name: Go build
        run: go build -o tanzia-api ./api
